### ISSUE TITLE
crash after Master Slave use

### ISSUE THREAD

**Issue by golddogh** [DeviationTX/deviation#919] opened 2019-08-24 10:48 UTC
My jumper displayed a message after use of master slave mode.
It wrote "too low battery can't save"
The battery was set on 12V, I tried to flash and impossible, so I put 12V and same issue. I retried to flash after that and now nothing happen the screen is black and the usb mode is now unavailable.

**Comment by TheRealMoeder** [comment] 2019-08-28 20:20
duplicate of #433

**Closed by TheRealMoeder** 2019-08-28 20:20 UTC
Labels: Bug, Major
